### ISSUE TITLE
supported operating systems?

### ISSUE THREAD

**Issue by sam0x17** [woodruffw/notify.cr#2]

**Comment by spencerwi** [comment]
Based on statements about using DBus, my guess is that this only supports Linux-like OSes, but there's not an explicit note on the repo.

**Comment by woodruffw** [comment]
Yeah. Right now, only DBus/Desktop Notifications clients are supported.

I think DBus is _technically_ cross platform, but for all practical purposes this library is currently Linux (and BSD?) only.

I'll add a note to the repo in a bit (including a request for help making it cross-platform).

**Comment by woodruffw** [comment]
https://github.com/woodruffw/notify.cr/commit/209310e8e8df1be6fbacd573547b7485b2924b72 contains the note.
