### ISSUE TITLE
Mention that signals are not supported

### ISSUE THREAD

**Issue by bew** [woodruffw/notify.cr#4]
I think you should mention that you do not support signals `NotificationClosed` & `ActionInvoked` as per http://www.galago-project.org/specs/notification/0.9/x408.html#signals.

_Mainly because the dbus shard does not yet support dbus signals I guess_

**Comment by woodruffw** [comment]
> Mainly because the dbus shard does not yet support dbus signals I guess

Yep, this is the underlying reason. I'll add them once the dbus shard gets them (maybe I'll work on that!), so I consider this an upstream issue.

Thanks for the report anyways!
